name: Create Self Hosted Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    name: Tag Release ${{ github.head_ref }} and Push Docker image to Docker Hub
    uses: codecov/gha-workflows/.github/workflows/create-self-hosted-release.yml@v1.0.0
    secrets: inherit

  push-image:
    needs: [create-release]
    uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.0.0
    secrets: inherit
    with:
      push_release: true
      repo: ${{ vars.CODECOV_IMAGE_V2 || 'codecov/self-hosted-frontend' }}
      cache_requirements: false
